### ISSUE TITLE
No handler found

### ISSUE THREAD

**Issue by gep13** [shanalikhan1/code-settings-sync#1]
I really like the idea of this extension, however, when I try to use it, I get the following:

![image](https://cloud.githubusercontent.com/assets/1271146/11812987/d88f5d6a-a336-11e5-87c5-97652f8f0ee6.png)

Do you have any ideas about what is going on here?

**Comment by shanalikhan1** [comment]
Actually i developed the extension and later on found out the node js modules are not available after publishing on user computer that are used to develop this extension. 
it would be good If you can help me in checking this issue.

**Comment by gep13** [comment]
I will certainly help out, if/when I can.

**Comment by shanalikhan1** [comment]
the issue is fixed.

**Comment by gep13** [comment]
I have just installed the latest version (although the version number didn't seem to be changed) and I now get prompted for entering the token, but after I do that, nothing happens.

When I try to update again, also nothing seems to happen.  When I go to gist.github.com, I don't see any newly created gists.

Any ideas?

**Comment by shanalikhan1** [comment]
can you please open %appdata%\Roaming\Code\User and see whats in the token text. the file is created if the file is created the token doesnt have spaces before and end. i had this problem before.

**Comment by gep13** [comment]
@shanalikhan1 yes, that file exists, and contains a token, with no spaces either side of the text.

**Comment by shanalikhan1** [comment]
Can you please verify that issue is solved now. Code updated

**Comment by gep13** [comment]
@shanalikhan1 yes, this now seems to be working! :smile: 

Follow up question...

Is it possible to sync the extensions that you have installed for Code?

**Comment by shanalikhan1** [comment]
extension sync is the major and most important feature i want to develop in this extension
As far of now i dont see any documentation to add extension from code. i am still looking in some way to inject extension else we have to wait for code new builds with new APIs to provide this features.
Thanks for helping me :)

**Comment by gep13** [comment]
That is great to hear that this is on your radar, I really hope that you can figure something out.

Let me know if there is anything else that you would like me to test out.

**Comment by shanalikhan1** [comment]
I am working on this for Windows. I will high appreciate if you can test it on linux or Mac machines and improve the extension for those Machines if there is any possibility. :)

**Comment by gep13** [comment]
@shanalikhan1 sorry, I only have Windows machines, I don't run any Linux or Mac machines :-(

**Comment by jpambrun** [comment]
I just installed version 0.0.9 (I never tried any other version) and got the "No handler" issue when trying to upload settings.

**Comment by shanalikhan1** [comment]
please paste your VSCode console error log here.
and which OS you are using ?

**Comment by jpambrun** [comment]
I am on Linux.

Is this the output you wanted ?

```
No handler found for the command: 'extension.updateSettings'. Ensure there is an activation event defined, if you are an extension.
e.doShow @ workbench.main.js:63
e.show @ workbench.main.js:63
e.onQuickOpenHiding @ workbench.main.js:63
e.invoke @ workbench.main.js:10
e.fire @ workbench.main.js:12
(anonymous function) @ workbench.main.js:71
```

**Comment by shanalikhan1** [comment]
There was some [issue](https://github.com/shanalikhan1/code-settings-sync/pull/5) regarding path in Linux and OSX and is fixed.
Let me know if you found any problem
