### ISSUE TITLE
Incompatible with OS X (And Linux?)

### ISSUE THREAD

**Issue by kedare** [shanalikhan1/code-settings-sync#2]
Hello,

I tried to synchronize my settings from my work computer (Windows 10) to my personal one (OS X 10.11) but I cannot get it to work.

When checking the logs, I see that it tries to use windows formatted paths :

Error: ENOENT: no such file or directory, open '/Users/kedareLibrary/Preference\Code\User\token.txt'
    at Error (native)

I suppose a simple fix should be to review all the path ( \ vs / and here we miss a "/" between the HOME and the final directory)

**Comment by shanalikhan1** [comment]
Hi,
I developed it in windows so unable to unable to test in other platforms.

Can you please update the extension and let me know if this working across multiple OS?

**Comment by kedare** [comment]
Sure I will check on OS X asap :)

**Comment by kedare** [comment]
I just tested, it's working fine except a little visual bug. :)

It's asking twice the Gist ID, except that for the first one (that open the token page on Github) is the token (It's just the prompt that shows Gist ID instead of Token)

**Comment by shanalikhan1** [comment]
Thanks its fixed now.
